package app.chalo.userprofile.utils

object UserProfileFeatureErrorCodes {

    const val UPDATE_PROFILE_USER_NOT_LOGGED_IN_ERROR = 200
    const val UPDATE_PROFILE_INVALID_DOB_ERROR = 201
    const val UPDATE_PROFILE_USER_DOES_NOT_EXIST_ERROR = 202
    const val UPDATE_PROFILE_ID_MISMATCH_ERROR = 203
    const val UPDATE_PROFILE_LOCAL_EXCEPTION_ERROR = 204
    const val UPDATE_PROFILE_SERVER_ERROR = 205
    const val UPDATE_PROFILE_RESPONSE_PARSE_EXCEPTION_ERROR = 206
    const val UPDATE_PROFILE_INVALID_RESPONSE_ERROR = 207

    const val UPDATE_PROFILE_PHOTO_INVALID_URL = 208
    const val UPDATE_PROFILE_PHOTO_LOCAL_ERROR = 209
    const val UPDATE_PROFILE_PHOTO_RESPONSE_PARSE_ERROR = 210
    const val UPDATE_PROFILE_PHOTO_SERVER_ERROR = 211
}
